server:
  port: 8080
  servlet:
    session:
      timeout: 10m

spring:

  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/mall
    username: root
    password: root

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  thymeleaf:
    enabled: true
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  h2:
    console:
      enabled: true
      path: /h2-console

session:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sessions
    username: sa
    password: password

zuul:
  routes:
    shop:
      path: /shop/**
      url: http://localhost:8080
