server:
  port: 8081

spring:
  application:
    name: rest_api

  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/mall
    username: root
    password: root
