server:
  port: 8080

spring:
  application:
    name: gateway

zuul:
  routes:
    rest_api:
      path: /api/**
      url: http://localhost:8081/api/
    mvc_app:
      path: /shop/**
      url: http://localhost:8082/


