server:
  port: 8082

spring:
  application:
    name: mvc_app

  thymeleaf:
    enabled: true
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
